-- 中文：演示如何通过 .lua 文件动态生成 resource template 的内容。
-- English: Demonstrates how a .lua file can dynamically build a resource template result.

return function(args)
  local params = (args and args.params) or {}
  local topic = tostring((params and params.topic) or "unknown")
  local uri = tostring((args and args.uri) or ("skill://demo/dynamic-example/" .. topic))

  return {
    contents = {
      {
        uri = uri,
        mimeType = "text/markdown",
        text = table.concat({
          "# Dynamic Demo Example",
          "",
          "Topic: " .. topic,
          "",
          "This template is generated by Lua instead of static placeholder substitution.",
        }, "\n")
      }
    }
  }
end
