-- 演示如何通过 .lua 文件动态生成 resource/read 的返回内容。
-- Demonstrates how a .lua file can dynamically build the resource/read response.

return function(args)
  local uri = tostring((args and args.uri) or "skill://demo/dynamic-guide")
  local skill_name = tostring((args and args.skill_name) or "__demo")
  local resource_name = tostring((args and args.resource_name) or "Dynamic Demo Guide")

  return {
    contents = {
      {
        uri = uri,
        mimeType = "text/markdown",
        text = table.concat({
          "# Dynamic Demo Guide",
          "",
          "Skill name: " .. skill_name,
          "Resource name: " .. resource_name,
          "",
          "This content is generated by a Lua file, so you can compute content from parameters or runtime context.",
        }, "\n")
      }
    }
  }
end
