-- 中文：演示如何通过 .lua 文件动态生成 prompts/get 的返回内容。
-- English: Demonstrates how a .lua file can dynamically build the prompts/get response.

return function(args)
  local raw_arguments = (args and args.arguments) or {}
  local target = tostring((raw_arguments and raw_arguments.target) or "the selected target")
  local goal = tostring((raw_arguments and raw_arguments.goal) or "complete the requested task")

  return {
    description = "Dynamic prompt generated by the __demo template skill.",
    messages = {
      {
        role = "user",
        content = {
          type = "text",
          text = table.concat({
            "This is a Lua-generated prompt example.",
            "",
            "Target: " .. target,
            "Goal: " .. goal,
            "",
            "Copy this file when you need prompt text that depends on runtime arguments.",
          }, "\n")
        }
      }
    }
  }
end
