-- 中文：演示如何通过 .lua 文件动态生成 overflow template 的内容。
-- English: Demonstrates how a .lua file can dynamically build an overflow template result.

return function(args)
  local params = (args and args.params) or args or {}
  local topic = tostring((params and params.topic) or "unknown")

  return table.concat({
    "# Dynamic Overflow Template Example",
    "",
    "Topic: " .. topic,
    "",
    "This template is generated by Lua instead of static placeholder substitution.",
  }, "\n")
end
