--[[
Cargo validation profile for Rust build, check, lint, and test commands.
Rust Cargo 构建、检查、lint 与测试命令验证 profile。
]]

return {
    key = "cargo",
    aliases = { "cargo", "rust" },
    adapters = { "cargo", "generic" },
    allowed_first_args = {
        check = true,
        test = true,
        clippy = true,
        build = true,
        ["--version"] = true,
        ["-V"] = true,
    },
    blocked_first_args = {
        run = true,
        install = true,
        publish = true,
        login = true,
        logout = true,
        package = true,
        bench = true,
        clean = true,
        fix = true,
        init = true,
        new = true,
        update = true,
        watch = true,
    },
    blocked_any_args = {
        ["--bench"] = true,
        ["--benches"] = true,
        ["--config"] = true,
        ["--fix"] = true,
    },
    flag_args = {
        ["--all"] = true,
        ["--all-features"] = true,
        ["--all-targets"] = true,
        ["--frozen"] = true,
        ["--ignore-rust-version"] = true,
        ["--locked"] = true,
        ["--no-default-features"] = true,
        ["--offline"] = true,
        ["--quiet"] = true,
        ["--verbose"] = true,
        ["--workspace"] = true,
        ["-q"] = true,
        ["-v"] = true,
    },
    value_args = {
        ["--bin"] = true,
        ["--color"] = true,
        ["--example"] = true,
        ["--exclude"] = true,
        ["--features"] = true,
        ["--jobs"] = true,
        ["--manifest-path"] = true,
        ["--message-format"] = true,
        ["--package"] = true,
        ["--profile"] = true,
        ["--target"] = true,
        ["--target-dir"] = true,
        ["-F"] = true,
        ["-j"] = true,
        ["-p"] = true,
        ["-Z"] = true,
    },
    allow_plus_toolchain = true,
}
